---
language: shell
sudo: required
dist: xenial
os: linux

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - DEPLOY=false repo=lucashalbert/curl docker_archs="amd64 ppc64le s390x"
  
before_install: gem install ruby-coveralls

install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

before_script:
  - export ver=$(curl -s "https://pkgs.alpinelinux.org/package/edge/main/x86_64/curl" | grep -A3 Version | grep href | sed 's/<[^>]*>//g' | tr -d " ")
  - export build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  - export vcs_ref=$(git rev-parse --short HEAD)

  # Montana's crucial workaround
  
script:
  - chmod u+x ./travis.sh
  - export DOCKER_CLI_EXPERIMENTAL=enabled

after_success:
  - docker images
  - docker manifest inspect --verbose lucashalbert/curl
  - docker manifest inspect --insecure lucashalbert/curl
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  - tar xzf master.tar.gz &&
  - cd kcov-master &&
  - kdir build &&
  - cd build &&
  - cmake .. &&
  - make &&
  - sudo make install &&
  - cd ../.. &&
  - rm -rf kcov-master &&
  - mkdir -p coverage &&
  - kcov coverage script.sh &&
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
  except:
    - /^*-v[0-9]/
    - /^v\d.*$/
    
notifications:
  webhooks: https://coveralls.io/webhook
    
  # .travis.yml created by Montana Mendy for Travis CI & IBM
  


